config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/products', to: 'products#index'
  get '/products/:id', to: 'products#show', as: :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Productos</h1>

<%= 1 + 1 %> <br>
<%= Date.today %> <br>
<%= @products.count %> <br>



<% @products.each do |product| %>
    <%= link_to product_path(product.id), class: 'product' do %>
        <h2><%= product.title %></h2>
        <span><%= product.price %>$</span>
    <% end %>
<% end %>

app/views/products/show.html.erb
<h1 class="title"> <%= @product.title %> </h1>
<p class="description"> <%= @product.description %> </p>

<span class="price"> <%= @product.price %> </span>

app/views/shared/_header.html.erb
<h1>Title!!! from _header.html.erb</h1>